import type { ChatThread } from './chat-types'

export const chatThreads: ChatThread[] = [
  {
    id: 'huyng-yesterday',
    initials: 'H',
    name: 'Huyng',
    customerName: 'Huyng 様',
    date: '昨日',
    plan: '季節の懐石コース',
    status: 'キャンセル',
    lastMsg: 'hello',
    messages: [
      {
        id: 'huyng-system',
        type: 'system',
        dateLabel: '6月15日',
        text: 'お申し込みありがとうございます。シェフからの承諾をお待ちください。',
      },
      {
        id: 'huyng-outgoing',
        type: 'outgoing',
        text: 'hello',
        time: '16:23',
      },
    ],
  },
  {
    id: 'tsukamoto-0603',
    initials: '塚',
    name: '塚本',
    customerName: '塚本 様',
    date: '6/3',
    plan: '季節の懐石コース',
    status: '承認済',
    lastMsg: 'test',
    messages: [
      {
        id: 'tsukamoto-0603-system',
        type: 'system',
        dateLabel: '6月3日',
        text: 'ご予約内容を確認しました。詳細の共有をお願いします。',
      },
      {
        id: 'tsukamoto-0603-outgoing',
        type: 'outgoing',
        text: 'test',
        time: '11:08',
      },
    ],
  },
  {
    id: 'tsukamoto-0601',
    initials: '塚',
    name: '塚本',
    customerName: '塚本 様',
    date: '6/1',
    plan: '季節の懐石コース',
    status: 'キャンセル',
    lastMsg: 'お申し込みありがとうございます。シェフからの承諾をお待ちください...',
    messages: [
      {
        id: 'tsukamoto-0601-system',
        type: 'system',
        dateLabel: '6月1日',
        text: 'お申し込みありがとうございます。シェフからの承諾をお待ちください。',
      },
    ],
  },
  {
    id: 'lishin-0423',
    initials: '李',
    name: '李信',
    customerName: '李信 様',
    date: '4/23',
    plan: '季節の懐石コース',
    status: '承認済',
    lastMsg: 'hi',
    messages: [
      {
        id: 'lishin-0423-system',
        type: 'system',
        dateLabel: '4月23日',
        text: 'ご予約を承認しました。当日の流れをご確認ください。',
      },
      {
        id: 'lishin-0423-outgoing',
        type: 'outgoing',
        text: 'hi',
        time: '09:12',
      },
    ],
  },
  {
    id: 'lishin-0415',
    initials: '李',
    name: '李信',
    customerName: '李信 様',
    date: '4/15',
    plan: '季節の懐石コース',
    status: '承認済',
    lastMsg: 'ぽんちゃんきたよ',
    messages: [
      {
        id: 'lishin-0415-system',
        type: 'system',
        dateLabel: '4月15日',
        text: 'ご予約を承認しました。集合場所は前日にご案内します。',
      },
      {
        id: 'lishin-0415-outgoing',
        type: 'outgoing',
        text: 'ぽんちゃんきたよ',
        time: '18:01',
      },
    ],
  },
  {
    id: 'lishin-0410',
    initials: '李',
    name: '李信',
    customerName: '李信 様',
    date: '4/10',
    plan: '季節の懐石コース',
    status: 'キャンセル',
    lastMsg: 'テスト',
    messages: [
      {
        id: 'lishin-0410-system',
        type: 'system',
        dateLabel: '4月10日',
        text: 'キャンセルが確定しました。必要であれば再予約をご検討ください。',
      },
      {
        id: 'lishin-0410-outgoing',
        type: 'outgoing',
        text: 'テスト',
        time: '13:40',
      },
    ],
  },
  {
    id: 'takenaka-0406',
    initials: '竹',
    name: '竹中　飛翔',
    customerName: '竹中　飛翔 様',
    date: '4/6',
    plan: '季節の懐石コース',
    status: '承認済',
    lastMsg: 'おす',
    messages: [
      {
        id: 'takenaka-0406-system',
        type: 'system',
        dateLabel: '4月6日',
        text: 'ご予約ありがとうございます。開始10分前までにご準備をお願いします。',
      },
      {
        id: 'takenaka-0406-outgoing',
        type: 'outgoing',
        text: 'おす',
        time: '07:15',
      },
    ],
  },
]
